# Generated by Django 4.2.4 on 2023-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="imgs")),
                ("desc", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="football", name="img", field=models.ImageField(upload_to="jpg"),
        ),
    ]
